### ISSUE TITLE
Multiple invocation of @HiltComposeNavigationFactory create method

### ISSUE THREAD

**Issue by shekaroppo** [LachlanMcKee/Hilt-Compose-Navigation-Factory#26]
I am facing issue where create of @HiltComposeNavigationFactory is getting called multiple time causing infinite invocation of compose. I am not sure what is triggering this but i followed exact same steps as your sample,

**Comment by LachlanMcKee** [comment]
hi @shekaroppo

sorry to hear that. I'm happy to help trying to resolve this. Out of interest is the project your trying to integrate this into public?

Failing that can you please tell me your versions of the following:
- Gradle
- Jetpack Compose
- Dagger/Dagger Hilt
- Android Studio version

**Comment by LachlanMcKee** [comment]
@shekaroppo I'm close to close this issue for now as you've not gotten back to me. if you're still having issues please reply and I will reopen the issue.
